package GUI;
import DB.DB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Extreme
 */
public class Add_Book_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Add_Book_GUI
     */
    public Add_Book_GUI() {
        initComponents();
        setResizable(false);
        
         try
        {
            int book3=0;
            Connection con = DB.myCon();
            Statement stmt =  con.createStatement();
            ResultSet res2 = stmt.executeQuery("SELECT lastbookid FROM idgenarate WHERE rawNo="+1+"");
            if (res2.next()) 
            {
                book3= Integer.parseInt(res2.getString("lastbookid"));
            }
             BID.setText("B"+book3);
            
        }
         catch (Exception e) {
              
               JOptionPane.showMessageDialog(this, "Data Base Error!","",JOptionPane.ERROR_MESSAGE);
                        
            }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        authortxt = new javax.swing.JTextField();
        isbntxt = new javax.swing.JTextField();
        noofpagetxt = new javax.swing.JTextField();
        pricetxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        categoryselect = new javax.swing.JComboBox();
        booktypeselect = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        shelfnotxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BID = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Book");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/title ori.jpg"))); // NOI18N

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Library Management System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Name");
        jLabel2.setBounds(30, 80, 31, 14);
        jLayeredPane2.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Author");
        jLabel3.setBounds(30, 120, 37, 14);
        jLayeredPane2.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("ISBN");
        jLabel4.setBounds(30, 160, 29, 14);
        jLayeredPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Catergory");
        jLabel5.setBounds(30, 200, 70, 14);
        jLayeredPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("No of Pages");
        jLabel7.setBounds(30, 250, 70, 14);
        jLayeredPane2.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Book Type");
        jLabel8.setBounds(30, 300, 70, 14);
        jLayeredPane2.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nametxt.setBounds(130, 80, 260, 20);
        jLayeredPane2.add(nametxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        authortxt.setBounds(130, 120, 260, 20);
        jLayeredPane2.add(authortxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        isbntxt.setBounds(130, 160, 260, 20);
        jLayeredPane2.add(isbntxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        noofpagetxt.setBounds(130, 250, 260, 20);
        jLayeredPane2.add(noofpagetxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pricetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricetxtActionPerformed(evt);
            }
        });
        pricetxt.setBounds(130, 340, 260, 20);
        jLayeredPane2.add(pricetxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset.gif"))); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(490, 370, 90, 30);
        jLayeredPane2.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/save.png"))); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(610, 370, 90, 30);
        jLayeredPane2.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/back1.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(560, 410, 80, 30);
        jLayeredPane2.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        categoryselect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Fiction", "Novels", "Short Stories", "Educational" }));
        categoryselect.setBounds(130, 200, 260, 20);
        jLayeredPane2.add(categoryselect, javax.swing.JLayeredPane.DEFAULT_LAYER);

        booktypeselect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Normal", "Reference" }));
        booktypeselect.setBounds(130, 300, 260, 20);
        jLayeredPane2.add(booktypeselect, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Shelf Number");
        jLabel10.setBounds(30, 400, 80, 20);
        jLayeredPane2.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        shelfnotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shelfnotxtActionPerformed(evt);
            }
        });
        shelfnotxt.setBounds(130, 400, 260, 20);
        jLayeredPane2.add(shelfnotxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Price");
        jLabel11.setBounds(30, 340, 80, 20);
        jLayeredPane2.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        BID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BID.setBounds(130, 40, 130, 10);
        jLayeredPane2.add(BID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel20.setText("New Book ID");
        jLabel20.setBounds(30, 40, 100, 14);
        jLayeredPane2.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(30, 40, 730, 450);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu2.setText("Navigate");

        jMenuItem8.setText("Home");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem2.setText("Manage Members");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Manage Books");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Manage Book Lending");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Manage Inventory");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Manage Newspaper Reocords");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Manage User Accounts");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-816)/2, (screenSize.height-638)/2, 816, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void pricetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pricetxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    
       DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
       Date date=new Date();
      
    

        
        String book_type=(String) booktypeselect.getSelectedItem();
        String category=(String) categoryselect.getSelectedItem();

        
        try{ 
        
        if (nametxt.getText().equals("") || authortxt.getText().equals("")||isbntxt.getText().equals("")||category.equals("Select")||noofpagetxt.getText().equals("")||book_type.equals("Select")||pricetxt.getText().equals("")||shelfnotxt.getText().equals("")) 
        {
              JOptionPane.showMessageDialog(this, "Please fill in all fields ", "",JOptionPane.WARNING_MESSAGE);
        }
        else if((Integer.parseInt(noofpagetxt.getText())<0))
        {
            JOptionPane.showMessageDialog(this, "Please fill the No of pages field correctly ", "",JOptionPane.WARNING_MESSAGE);
        }
        else if((Double.parseDouble(pricetxt.getText())<0))
        {
            JOptionPane.showMessageDialog(this, "Please fill the Price field correctly ", "",JOptionPane.WARNING_MESSAGE);
        }
        else if((Integer.parseInt(shelfnotxt.getText())<0))
        {
            JOptionPane.showMessageDialog(this, "Please fill the No of Shelf No correctly ", "",JOptionPane.WARNING_MESSAGE);
        }
        
     
        else
        {    
               
            String name=nametxt.getText();
        String author=authortxt.getText();
        String isbn=isbntxt.getText();
        
        int no_of_pages=Integer.parseInt(noofpagetxt.getText());
        int shelf_no=Integer.parseInt((shelfnotxt.getText()));
        double price=Double.parseDouble(pricetxt.getText());
        
        Connection con = DB.myCon();
            Statement stmt = con.createStatement();
             int bookid=0;
            ResultSet res = stmt.executeQuery("SELECT lastbookid FROM idgenarate WHERE rawNo="+1+"");
            while (res.next()) 
            {
                bookid = Integer.parseInt(res.getString("lastbookid"));
            }
            String query1="INSERT into Book1 Values('B"+bookid+"','"+name+"','"+author+"','"+isbn+"','"+category+"','"+dateFormat.format(date)+"',"+no_of_pages+",'"+book_type+"',"+price+","+shelf_no+",'Available')";
         
            stmt.executeUpdate(query1);
           JOptionPane.showMessageDialog(this,"Add BookDetails Successfully Book ID = B"+bookid);
           bookid=bookid+1;
           String qry="update idgenarate set lastbookid='"+bookid+"' where rawNo="+1;
        stmt.executeUpdate(qry);
         int book1=0;
            
            ResultSet res2 = stmt.executeQuery("SELECT lastbookid FROM idgenarate WHERE rawNo="+1+"");
            while (res2.next()) 
            {
                book1= Integer.parseInt(res2.getString("lastbookid"));
            }
             BID.setText("B"+book1);
        
        
         nametxt.setText("");
        authortxt.setText("");
        isbntxt.setText("");
        categoryselect.setSelectedItem("Select");
        noofpagetxt.setText("");
        pricetxt.setText("");
        booktypeselect.setSelectedItem("Select");
        shelfnotxt.setText("");
        
        }
        
        }
           catch (NumberFormatException n) 
            {
                JOptionPane.showMessageDialog(this, " Only Enter Numbers to Price and No of pages and shelf  fields!","",JOptionPane.ERROR_MESSAGE);
            }
         catch (Exception e)
            {
              
               JOptionPane.showMessageDialog(this, ""+e.getMessage()+" Error,  Book Not Added!","",JOptionPane.ERROR_MESSAGE);
                        
            }
      
 
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         nametxt.setText("");
        authortxt.setText("");
        isbntxt.setText("");
        categoryselect.setSelectedItem("Select");
        noofpagetxt.setText("");
        pricetxt.setText("");
        booktypeselect.setSelectedItem("Select");
        shelfnotxt.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       new Manage_Books_GUI().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void shelfnotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shelfnotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shelfnotxtActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
       new Manage_Book_Lending().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       new Manage_Inventory_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new Manage_Members_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       new Manage_Books_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new Manage_Newspaper_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
      new Manage_User_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        new Home_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Book_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Book_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Book_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Book_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Add_Book_GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BID;
    private javax.swing.JTextField authortxt;
    private javax.swing.JComboBox booktypeselect;
    private javax.swing.JComboBox categoryselect;
    private javax.swing.JTextField isbntxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField noofpagetxt;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JTextField shelfnotxt;
    // End of variables declaration//GEN-END:variables
}
