package GUI;


import DB.DB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Extreme
 */
public class Add_Member_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Add_Member_GUI
     */
    public Add_Member_GUI() {
        initComponents();
        setResizable(false);
        
        try
        {
            int smemberid3=0;
            Connection con = DB.myCon();
            Statement stmt =  con.createStatement();
            ResultSet res2 = stmt.executeQuery("SELECT lastmemberid FROM idgenarate WHERE rawNo="+1+"");
            while (res2.next()) 
            {
                smemberid3= Integer.parseInt(res2.getString("lastmemberid"));
            }
             SID.setText("S"+smemberid3);
            TID.setText("T"+smemberid3);
        }
         catch (Exception e) {
              
               JOptionPane.showMessageDialog(this, ""+e.getMessage()+" Error,!","",JOptionPane.ERROR_MESSAGE);
                        
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        SID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Sfnametxt = new javax.swing.JTextField();
        Slnametxt = new javax.swing.JTextField();
        Saddresstxt = new javax.swing.JTextField();
        Sgenderselect = new javax.swing.JComboBox();
        Scontactnotxt = new javax.swing.JTextField();
        Semailtxt = new javax.swing.JTextField();
        Sgradetxt = new javax.swing.JTextField();
        SDOB = new com.toedter.calendar.JDateChooser();
        studentsave = new javax.swing.JButton();
        studentreset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Tfnametxt = new javax.swing.JTextField();
        Tlnametxt = new javax.swing.JTextField();
        Taddresstxt = new javax.swing.JTextField();
        Tgenderselect = new javax.swing.JComboBox();
        Tcontactnotxt = new javax.swing.JTextField();
        Temailtxt = new javax.swing.JTextField();
        Tsubjecttxt = new javax.swing.JTextField();
        TDOB = new com.toedter.calendar.JDateChooser();
        teachersave = new javax.swing.JButton();
        teacherreset = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        TID = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Member");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Library Management System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        jTabbedPane4.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTabbedPane4.setName("");

        jLayeredPane2.setBackground(new java.awt.Color(204, 204, 204));
        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Students", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        SID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SID.setText("ID");
        SID.setBounds(140, 40, 100, 17);
        jLayeredPane2.add(SID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Last  Name");
        jLabel3.setBounds(20, 110, 70, 20);
        jLayeredPane2.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Address");
        jLabel4.setBounds(20, 150, 50, 20);
        jLayeredPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Date of Birth");
        jLabel5.setBounds(20, 190, 69, 14);
        jLayeredPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Gender");
        jLabel6.setBounds(20, 230, 39, 14);
        jLayeredPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Contact No");
        jLabel7.setBounds(20, 270, 59, 20);
        jLayeredPane2.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Email");
        jLabel8.setBounds(20, 310, 31, 14);
        jLayeredPane2.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Grade");
        jLabel10.setBounds(20, 344, 40, 30);
        jLayeredPane2.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sfnametxt.setBounds(140, 70, 240, 20);
        jLayeredPane2.add(Sfnametxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Slnametxt.setBounds(140, 110, 240, 20);
        jLayeredPane2.add(Slnametxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Saddresstxt.setBounds(140, 150, 240, 20);
        jLayeredPane2.add(Saddresstxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Sgenderselect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Male", "Female" }));
        Sgenderselect.setBounds(140, 230, 240, 20);
        jLayeredPane2.add(Sgenderselect, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Scontactnotxt.setBounds(140, 270, 240, 20);
        jLayeredPane2.add(Scontactnotxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Semailtxt.setBounds(140, 310, 240, 20);
        jLayeredPane2.add(Semailtxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Sgradetxt.setBounds(140, 350, 240, 20);
        jLayeredPane2.add(Sgradetxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        SDOB.setBounds(140, 190, 240, 20);
        jLayeredPane2.add(SDOB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        studentsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/save.png"))); // NOI18N
        studentsave.setText("Save");
        studentsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsaveActionPerformed(evt);
            }
        });
        studentsave.setBounds(420, 380, 80, 25);
        jLayeredPane2.add(studentsave, javax.swing.JLayeredPane.DEFAULT_LAYER);

        studentreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset.gif"))); // NOI18N
        studentreset.setText("Reset");
        studentreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentresetActionPerformed(evt);
            }
        });
        studentreset.setBounds(320, 380, 80, 25);
        jLayeredPane2.add(studentreset, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("First Name");
        jLabel9.setBounds(20, 70, 70, 14);
        jLayeredPane2.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("New Student ID");
        jLabel11.setBounds(20, 40, 90, 14);
        jLayeredPane2.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane4.addTab("Student", jLayeredPane2);

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Teachers", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("First Name");
        jLabel12.setBounds(20, 100, 70, 14);
        jLayeredPane4.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Last  Name");
        jLabel13.setBounds(20, 150, 70, 14);
        jLayeredPane4.add(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Address");
        jLabel14.setBounds(20, 180, 60, 20);
        jLayeredPane4.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("Date of Birth");
        jLabel15.setBounds(20, 220, 69, 20);
        jLayeredPane4.add(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("Gender");
        jLabel16.setBounds(20, 250, 40, 20);
        jLayeredPane4.add(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText("Contact No");
        jLabel17.setBounds(20, 290, 59, 20);
        jLayeredPane4.add(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("Email");
        jLabel18.setBounds(21, 314, 40, 30);
        jLayeredPane4.add(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel20.setText("Subject");
        jLabel20.setBounds(20, 350, 50, 20);
        jLayeredPane4.add(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Tfnametxt.setBounds(140, 100, 240, 20);
        jLayeredPane4.add(Tfnametxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Tlnametxt.setBounds(140, 140, 240, 20);
        jLayeredPane4.add(Tlnametxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Taddresstxt.setBounds(140, 180, 240, 20);
        jLayeredPane4.add(Taddresstxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Tgenderselect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Male", "Female" }));
        Tgenderselect.setBounds(140, 250, 240, 20);
        jLayeredPane4.add(Tgenderselect, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Tcontactnotxt.setBounds(140, 290, 240, 20);
        jLayeredPane4.add(Tcontactnotxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Temailtxt.setBounds(140, 320, 240, 20);
        jLayeredPane4.add(Temailtxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Tsubjecttxt.setBounds(140, 350, 240, 20);
        jLayeredPane4.add(Tsubjecttxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        TDOB.setBounds(140, 220, 240, 20);
        jLayeredPane4.add(TDOB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        teachersave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/save.png"))); // NOI18N
        teachersave.setText("Save");
        teachersave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachersaveActionPerformed(evt);
            }
        });
        teachersave.setBounds(430, 380, 80, 25);
        jLayeredPane4.add(teachersave, javax.swing.JLayeredPane.DEFAULT_LAYER);

        teacherreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset.gif"))); // NOI18N
        teacherreset.setText("Reset");
        teacherreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherresetActionPerformed(evt);
            }
        });
        teacherreset.setBounds(330, 380, 80, 25);
        jLayeredPane4.add(teacherreset, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("New Teacher ID");
        jLabel19.setBounds(20, 50, 90, 14);
        jLayeredPane4.add(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        TID.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        TID.setText("ID");
        TID.setBounds(150, 50, 100, 17);
        jLayeredPane4.add(TID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane4.addTab("Teacher", jLayeredPane4);

        jTabbedPane4.setBounds(110, 40, 540, 450);
        jLayeredPane1.add(jTabbedPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/back1.png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        back.setBounds(690, 280, 90, 40);
        jLayeredPane1.add(back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/title ori.jpg"))); // NOI18N

        jMenu2.setText("Navigate");

        jMenuItem8.setText("Home");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem2.setText("Manage Members");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Manage Books");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Manage Book Lending");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Manage Inventory");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Manage Newspaper Reocords");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Manage User Accounts");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-816)/2, (screenSize.height-638)/2, 816, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void teachersaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersaveActionPerformed
      
        try{
        
        String Gender=(String) Tgenderselect.getSelectedItem();
         Date DOB=TDOB.getDate();
         Date today=new Date();
         DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        String Email1=Temailtxt.getText();
        
        
        
        if (Tfnametxt.getText().equals("") || Tlnametxt.getText().equals("")||Taddresstxt.getText().equals("")||Tcontactnotxt.getText().equals("")||Temailtxt.getText().equals("")||Gender.equals("Telect")||Tsubjecttxt.getText().equals("")||TDOB.getDate()==null) 
        {
              JOptionPane.showMessageDialog(this, "Please fill in all fields ", "",JOptionPane.WARNING_MESSAGE);
        }
        
        
        else if(!(Tcontactnotxt.getText().length()==10)||(Integer.parseInt(Tcontactnotxt.getText())<0))
        {
            JOptionPane.showMessageDialog(this, "Please fill the contact number field correctly ", "",JOptionPane.WARNING_MESSAGE);
        }
        
         
         else if(!((Email1.indexOf("@")>0)&&((Email1.indexOf(".")-Email1.indexOf("@"))>0)&&(((Email1.length()-1)-Email1.indexOf("."))>1)))
        {
            JOptionPane.showMessageDialog(this, "Please fill the Email field correctly ", "",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            
            
        String Fname=Tfnametxt.getText();
        String Lname=Tlnametxt.getText();
        String Address=Taddresstxt.getText();
        int ContactNo=Integer.parseInt(Tcontactnotxt.getText());
        // Long ContactNo=Long.parseLong(Tcontactnotxt.getText());
        String Subject=Tsubjecttxt.getText();
        String Email=Temailtxt.getText();
        String DateOfBirth=(String) dateFormat.format(DOB);
        String Today=(String) dateFormat.format(today); 
        
        
        Connection con = DB.myCon();
        Statement stmt =  con.createStatement();
        int tmemberid=0;
        ResultSet res = stmt.executeQuery("SELECT lastmemberid FROM idgenarate WHERE rawNo=1");
            if (res.next()) 
            {
                tmemberid= Integer.parseInt(res.getString("lastmemberid"));
            }
            
        String query1="INSERT into member  Values('T"+tmemberid+"')";
            
        String query2="INSERT into teacher (TmemberID,Fname,Lname,Address,DateOfBirth,DateOfRegistration,Gender,Email,ContactNumber,Subject,NoOfBooks) Values('T"+tmemberid+"','"+Fname+"','"+Lname+"','"+Address+"','"+DateOfBirth+"','"+Today+"','"+Gender+"','"+Email+"','"+Tcontactnotxt.getText()+"','"+Subject+"',0)";
        
        stmt.executeUpdate(query1);
        stmt.executeUpdate(query2);
            
           JOptionPane.showMessageDialog(this,"Teacher Member Details added Successfully Member ID = T"+tmemberid);
           
        tmemberid=tmemberid+1;
        String qry="update idgenarate set lastmemberid='"+tmemberid+"' where rawNo="+1;
        stmt.executeUpdate(qry);
        
        
            int smemberid4=0;
            ResultSet res2 = stmt.executeQuery("SELECT lastmemberid FROM idgenarate WHERE rawNo="+1+"");
            if (res2.next()) 
            {
                smemberid4= Integer.parseInt(res2.getString("lastmemberid"));
            }
            SID.setText("S"+smemberid4);
            TID.setText("T"+smemberid4);
        
        Tfnametxt.setText("");
        Tlnametxt.setText("");
        Taddresstxt.setText("");
        Tcontactnotxt.setText("");
        Tsubjecttxt.setText("");
        Temailtxt.setText("");
        TDOB.setCalendar(null);
        Tgenderselect.setSelectedItem("Select");   
            
        }
        }  
            catch (NumberFormatException n) 
             {
            JOptionPane.showMessageDialog(this, " Error Enter Numbers to contact No field!","",JOptionPane.ERROR_MESSAGE);
             }
         catch (Exception e) {
              
               JOptionPane.showMessageDialog(this, ""+e.getMessage()+" Error,  Teacher Not Added!","",JOptionPane.ERROR_MESSAGE);
                        
            }
        
    }//GEN-LAST:event_teachersaveActionPerformed

    private void studentsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsaveActionPerformed
       
          try
          {  
        String Gender=(String) Sgenderselect.getSelectedItem();
         Date DOB=SDOB.getDate();
         Date today=new Date();
         DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        
         
         String Email1=Semailtxt.getText();
        
        if (Sfnametxt.getText().equals("") || Slnametxt.getText().equals("")||Saddresstxt.getText().equals("")||Scontactnotxt.getText().equals("")||Semailtxt.getText().equals("")||Gender.equals("Select")||Sgradetxt.getText().equals("")||SDOB.getDate()==null) 
        {
              JOptionPane.showMessageDialog(this, "Please fill in all fields ", "",JOptionPane.WARNING_MESSAGE);
        }
        
        else if(!(Scontactnotxt.getText().length()==10)||(Long.parseLong(Scontactnotxt.getText())<0))
        {
            JOptionPane.showMessageDialog(this, "Please fill the contact number field correctly ", "",JOptionPane.WARNING_MESSAGE);
        }
        
         else if((Integer.parseInt(Sgradetxt.getText())<8)&&(Integer.parseInt(Sgradetxt.getText())<=13))
        {
            JOptionPane.showMessageDialog(this, "Please fill the Grade number field correctly ", "",JOptionPane.WARNING_MESSAGE);
        }
         
         else if(!((Email1.indexOf("@")>0)&&((Email1.indexOf(".")-Email1.indexOf("@"))>0)&&(((Email1.length()-1)-Email1.indexOf("."))>1)))
        {
            JOptionPane.showMessageDialog(this, "Please fill the Email field correctly ", "",JOptionPane.WARNING_MESSAGE);
        }
        

         
         
         else
        {
         
            
        String Fname=Sfnametxt.getText();
        String Lname=Slnametxt.getText();
        String Address=Saddresstxt.getText();
        int ContactNo=Integer.parseInt(Scontactnotxt.getText());
        int Grade=Integer.parseInt(Sgradetxt.getText());
        String Email=Semailtxt.getText();
        String DateOfBirth=(String) dateFormat.format(DOB);
        String Today=(String) dateFormat.format(today);
        
        Connection con = DB.myCon();
        Statement stmt =  con.createStatement();
        
            int smemberid=0;
            ResultSet res = stmt.executeQuery("SELECT lastmemberid FROM idgenarate WHERE rawNo="+1+"");
            if (res.next()) 
            {
                smemberid= Integer.parseInt(res.getString("lastmemberid"));
            }
            String query1="INSERT into member  Values('S"+smemberid+"')";
            String query2="INSERT into student (SmemberID,Fname,Lname,Address,DateOfBirth,DateOfRegistration,Gender,Email,ContactNumber,Grade,NoOfBooks) Values('S"+smemberid+"','"+Fname+"','"+Lname+"','"+Address+"','"+DateOfBirth+"','"+Today+"','"+Gender+"','"+Email+"','"+Scontactnotxt.getText()+"',"+Grade+",0)";
         
           stmt.executeUpdate(query1);
           stmt.executeUpdate(query2);
           
           JOptionPane.showMessageDialog(this,"Student Member Details added Successfully Member ID= S"+smemberid);
          
           smemberid=smemberid+1;
           String qry="update idgenarate set lastmemberid="+smemberid+" where rawNo=1";
           stmt.executeUpdate(qry);
          
            int smemberid4=0;
            
            ResultSet res2 = stmt.executeQuery("SELECT lastmemberid FROM idgenarate WHERE rawNo="+1+"");
            if (res2.next()) 
            {
                smemberid4= Integer.parseInt(res2.getString("lastmemberid"));
            }
             SID.setText("S"+smemberid4);
             TID.setText("T"+smemberid4);
          

        
        Sfnametxt.setText("");
        Slnametxt.setText("");
        Saddresstxt.setText("");
        Scontactnotxt.setText("");
        Sgradetxt.setText("");
        Semailtxt.setText("");
        SDOB.setCalendar(null);
        Sgenderselect.setSelectedItem("Select");   
            
        }
          
          }
        catch (NumberFormatException n) 
            {
                    JOptionPane.showMessageDialog(this, " Error Enter Numbers to Contact Number and Grade fields!","",JOptionPane.ERROR_MESSAGE);
            }
        catch (Exception e)
            {
              
               JOptionPane.showMessageDialog(this, ""+e.getMessage()+" Error,  Student Not Added!","",JOptionPane.ERROR_MESSAGE);
                        
            }
        
    }//GEN-LAST:event_studentsaveActionPerformed

    private void studentresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentresetActionPerformed
        Sfnametxt.setText("");
        Slnametxt.setText("");
        Saddresstxt.setText("");
        Scontactnotxt.setText("");
        Sgradetxt.setText("");
        Semailtxt.setText("");
        SDOB.setCalendar(null);
         Sgenderselect.setSelectedItem("Select");   
    }//GEN-LAST:event_studentresetActionPerformed

    private void teacherresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherresetActionPerformed
          Tfnametxt.setText("");
        Tlnametxt.setText("");
        Taddresstxt.setText("");
        Tcontactnotxt.setText("");
        Tsubjecttxt.setText("");
        Temailtxt.setText("");
        TDOB.setCalendar(null);
         Tgenderselect.setSelectedItem("Select");      
            
    }//GEN-LAST:event_teacherresetActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       new Manage_Members_GUI().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        new Home_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new Manage_Members_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new Manage_Books_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new Manage_Book_Lending().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new Manage_Inventory_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new Manage_Newspaper_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new Manage_User_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Member_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Member_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Member_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Member_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Add_Member_GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser SDOB;
    private javax.swing.JLabel SID;
    private javax.swing.JTextField Saddresstxt;
    private javax.swing.JTextField Scontactnotxt;
    private javax.swing.JTextField Semailtxt;
    private javax.swing.JTextField Sfnametxt;
    private javax.swing.JComboBox Sgenderselect;
    private javax.swing.JTextField Sgradetxt;
    private javax.swing.JTextField Slnametxt;
    private com.toedter.calendar.JDateChooser TDOB;
    private javax.swing.JLabel TID;
    private javax.swing.JTextField Taddresstxt;
    private javax.swing.JTextField Tcontactnotxt;
    private javax.swing.JTextField Temailtxt;
    private javax.swing.JTextField Tfnametxt;
    private javax.swing.JComboBox Tgenderselect;
    private javax.swing.JTextField Tlnametxt;
    private javax.swing.JTextField Tsubjecttxt;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JButton studentreset;
    private javax.swing.JButton studentsave;
    private javax.swing.JButton teacherreset;
    private javax.swing.JButton teachersave;
    // End of variables declaration//GEN-END:variables
}
