/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DB;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Extreme
 */
public class Manage_Book_Lending extends javax.swing.JFrame {

    /**
     * Creates new form Manage_Book_Lending
     */
    public Manage_Book_Lending() {
        initComponents();
        disabling();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        refnotxt = new javax.swing.JTextField();
        memberidtxt = new javax.swing.JTextField();
        bookid = new javax.swing.JTextField();
        statues = new javax.swing.JTextField();
        latedaystxt = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        search = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        addmember = new javax.swing.JButton();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        edit = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        back = new javax.swing.JButton();
        DOBr = new com.toedter.calendar.JDateChooser();
        DOD = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        finetxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Bok Lending");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Library Management System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Manage Book Lending", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Reference No");
        jLabel2.setBounds(20, 50, 80, 14);
        jLayeredPane2.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Member ID");
        jLabel3.setBounds(20, 84, 70, 30);
        jLayeredPane2.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Book ID");
        jLabel4.setBounds(20, 140, 70, 14);
        jLayeredPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Borrowed Date");
        jLabel5.setBounds(20, 184, 90, 30);
        jLayeredPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Due Date");
        jLabel6.setBounds(20, 240, 80, 14);
        jLayeredPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Status");
        jLabel8.setBounds(20, 284, 100, 30);
        jLayeredPane2.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Fine Amount");
        jLabel10.setBounds(20, 390, 100, 14);
        jLayeredPane2.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("No of Late Dates");
        jLabel12.setBounds(20, 330, 120, 20);
        jLayeredPane2.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        refnotxt.setBounds(140, 50, 230, 20);
        jLayeredPane2.add(refnotxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        memberidtxt.setBounds(140, 100, 230, 20);
        jLayeredPane2.add(memberidtxt, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bookid.setBounds(140, 150, 230, 20);
        jLayeredPane2.add(bookid, javax.swing.JLayeredPane.DEFAULT_LAYER);
        statues.setBounds(140, 290, 230, 20);
        jLayeredPane2.add(statues, javax.swing.JLayeredPane.DEFAULT_LAYER);
        latedaystxt.setBounds(140, 340, 230, 20);
        jLayeredPane2.add(latedaystxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Search-Search-icon1`.png"))); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        search.setBounds(20, 20, 90, 25);
        jLayeredPane3.add(search, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/view.png"))); // NOI18N
        jButton2.setText("View All");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(120, 20, 90, 25);
        jLayeredPane3.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane3.setBounds(470, 40, 240, 70);
        jLayeredPane2.add(jLayeredPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        addmember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/309px-Books-aj.svg_aj_ashton_01f.svg.png"))); // NOI18N
        addmember.setText("Lend Book");
        addmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmemberActionPerformed(evt);
            }
        });
        addmember.setBounds(490, 150, 220, 40);
        jLayeredPane2.add(addmember, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset.png"))); // NOI18N
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        edit.setBounds(20, 10, 210, 25);
        jLayeredPane4.add(edit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/edit.png"))); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        update.setBounds(20, 50, 90, 25);
        jLayeredPane4.add(update, javax.swing.JLayeredPane.DEFAULT_LAYER);

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/delete.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        delete.setBounds(140, 50, 90, 25);
        jLayeredPane4.add(delete, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane4.setBounds(470, 300, 240, 90);
        jLayeredPane2.add(jLayeredPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset.gif"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        reset.setBounds(480, 410, 90, 30);
        jLayeredPane2.add(reset, javax.swing.JLayeredPane.DEFAULT_LAYER);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/back1.png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        back.setBounds(620, 410, 90, 30);
        jLayeredPane2.add(back, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DOBr.setBounds(140, 190, 240, 20);
        jLayeredPane2.add(DOBr, javax.swing.JLayeredPane.DEFAULT_LAYER);
        DOD.setBounds(140, 240, 240, 20);
        jLayeredPane2.add(DOD, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/309px-Books-aj.svg_aj_ashton_01f.svg.png"))); // NOI18N
        jButton1.setText("Return Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(490, 220, 220, 40);
        jLayeredPane2.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        finetxt.setBounds(140, 390, 230, 20);
        jLayeredPane2.add(finetxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane2.setBounds(20, 30, 750, 460);
        jLayeredPane1.add(jLayeredPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/title ori.jpg"))); // NOI18N

        jMenu2.setText("Navigate");

        jMenuItem8.setText("Home");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem2.setText("Manage Members");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Manage Books");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Manage Book Lending");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Manage Inventory");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Manage Newspaper Reocords");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Manage User Accounts");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-816)/2, (screenSize.height-638)/2, 816, 638);
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
       try
       {
        
        if (refnotxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the REference number you wish to Search ", "", JOptionPane.OK_OPTION);
        } else
        {

            
                int ref = Integer.parseInt(refnotxt.getText());
                Connection con = DB.myCon();
                Statement S = con.createStatement();
                ResultSet rs = null;
                //selecting member table   
              


                    rs = S.executeQuery("SELECT * FROM borrow WHERE refno=" + ref + "");
                    if (rs.next()) {
                        enabling();
                        memberidtxt.setText(rs.getString("memberid"));
                        bookid.setText(rs.getString("bookid"));
                       
                        DOBr.setDate(rs.getDate("Borrowdate"));
                        
                        DOD.setDate(rs.getDate("duedate"));
                        statues.setText(rs.getString("statues"));
                        finetxt.setText(rs.getString("fineammount"));
                        latedaystxt.setText(rs.getString("latedays"));
                        



                 
                    } 
                    else
                    {
                        JOptionPane.showMessageDialog(this, " No such record  !", "", JOptionPane.OK_OPTION);
                        refnotxt.setText("");
                    }
                } 
               

                //displayinig values

            }
       catch (Exception e) {
                JOptionPane.showMessageDialog(this, "" + e.getMessage() + " Error,  ", "", JOptionPane.OK_OPTION);
            }
        
    }//GEN-LAST:event_searchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Book_Lend_ViewAll().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmemberActionPerformed
        new Manage_Lend_Process_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addmemberActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed

 try
       {
        
        if (refnotxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the REference number you wish to Search ", "", JOptionPane.OK_OPTION);
        } else
        {

            
                int ref = Integer.parseInt(refnotxt.getText());
                Connection con = DB.myCon();
                Statement S = con.createStatement();
                ResultSet rs = null;
                //selecting member table   
              


                    rs = S.executeQuery("SELECT * FROM borrow WHERE refno=" + ref + "");
                    if (rs.next()) {
                        enabling();
                        
                           update.setEnabled(true);
                    delete.setEnabled(true);
                   
                    
                        
                        
                        memberidtxt.setText(rs.getString("memberid"));
                        bookid.setText(rs.getString("bookid"));
                       
                        DOBr.setDate(rs.getDate("Borrowdate"));
                        
                        DOD.setDate(rs.getDate("duedate"));
                        statues.setText(rs.getString("statues"));
                        finetxt.setText(rs.getString("fineammount"));
                        latedaystxt.setText(rs.getString("latedays"));
                        



                 
                    } 
                    else
                    {
                        JOptionPane.showMessageDialog(this, " No such record  !", "", JOptionPane.OK_OPTION);
                        refnotxt.setText("");
                    }
                } 
               

                //displayinig values

            }
       catch (Exception e) {
                JOptionPane.showMessageDialog(this, "" + e.getMessage() + " Error,  ", "", JOptionPane.OK_OPTION);
            }

                //selecting member table   
            
                 



                   

                //displayinig values

         
        


    }//GEN-LAST:event_editActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
      
         int b = JOptionPane.showConfirmDialog(null, "Do you want to Update ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (b == 0) {
        
        
        try {
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");




        String ref = refnotxt.getText();
       


      

            if (memberidtxt.getText().equals("") || bookid.getText().equals("") || finetxt.getText().equals("") || statues.getText().equals("") || refnotxt.getText().equals("") || latedaystxt.getText().equals("") || DOD.getDate() == null  ) {
                JOptionPane.showMessageDialog(this, "Please fill in all fields ", "", JOptionPane.WARNING_MESSAGE);
            }
            else if((Integer.parseInt(latedaystxt.getText())<0))
            {
            JOptionPane.showMessageDialog(this, "Please fill the Late Days field correctly ", "",JOptionPane.WARNING_MESSAGE);
            }
            else if((Double.parseDouble(finetxt.getText())<0))
            {
            JOptionPane.showMessageDialog(this, "Please fill the Fine ammount field correctly ", "",JOptionPane.WARNING_MESSAGE);
            }
            else {

                
                    String memberid = memberidtxt.getText();
                    String bookidq = bookid.getText();

                    
                    int latedays = Integer.parseInt(latedaystxt.getText());
                    String statuesq = statues.getText();
                    
                    Double fine = Double.parseDouble(finetxt.getText());
                    
                    Date D1 = DOBr.getDate();
                   
                    Date D3 = DOD.getDate();
                    
                    String Dateborrow = (String) dateFormat.format(D1);
                   
                    String Datedue = (String) dateFormat.format(D3);


                    Connection con = DB.myCon();
                    Statement stmt = con.createStatement();
                 
                    String query1="UPDATE borrow SET    latedays="+latedays+", fineammount="+fine+",borrowdate='"+Dateborrow+"',duedate='"+Datedue+"' WHERE refno = '"+ref+"'";
                    stmt.executeUpdate(query1);


                     JOptionPane.showMessageDialog(this,"Updated Successfully");


            
            }
       
       }
            catch (NumberFormatException n) 
                {
     JOptionPane.showMessageDialog(this, "Only Enter Numbers to relavant fields!"+n.getMessage(),"",JOptionPane.ERROR_MESSAGE);
                }
                 catch (Exception e) {

                    JOptionPane.showMessageDialog(this, "" + e.getMessage() + " Error,  Details Not Updated!", "", JOptionPane.OK_OPTION);

                }
        }


    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed


        


        
            try {
                
                int b = JOptionPane.showConfirmDialog(null, "Do you want to Delete ?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (b == 0) {
                
                String ref = refnotxt.getText();
                String mid="";
                String bid="";
                String q3="";
                String q4="";
                int noofbooks=0;
                Connection con = DB.myCon();
                Statement S = con.createStatement();
         ResultSet rs = S.executeQuery("SELECT memberid,bookid FROM borrow WHERE refno=" + ref + "");
                    if (rs.next()) {
                        
                        mid=rs.getString("memberid");
                        bid=rs.getString("bookid");
                    }

                     
                    String q1 = ("DELETE FROM borrow WHERE refno = '" +ref+ "'");
                    String q2="UPDATE book1 SET  statues ='Available' WHERE bookid ='"+bid+"'";
                    
                    S.executeUpdate(q1);
                    S.executeUpdate(q2);
                    
                    if(mid.charAt(0)=='S')
          {
               q4="SELECT NoOfBooks FROM student WHERE SmemberID='"+mid+"'";
                    rs=S.executeQuery(q4);
                    if(rs.next())
                    {
                        noofbooks=Integer.parseInt(rs.getString("NoOfBooks")); 
                            noofbooks--;
                    }
                q3="UPDATE student SET  NoOfBooks ="+noofbooks+" WHERE SmemberID ='"+mid+"'";
                S.executeUpdate(q3);
          }
          if(mid.charAt(0)=='T')
          {
                q4="SELECT NoOfBooks FROM teacher WHERE TmemberID='"+mid+"'";
                 rs=S.executeQuery(q4);
                    if(rs.next())
                    {
                        noofbooks=Integer.parseInt(rs.getString("NoOfBooks")); 
                            noofbooks--;
                    }
                q3="UPDATE teacher SET  NoOfBooks ="+noofbooks+" WHERE TmemberID ='"+mid+"'";
                S.executeUpdate(q3);
          }
                    
                    

                    JOptionPane.showMessageDialog(null, " Record successfully Deleted");

                    reseting();
                    disabling();
                    refnotxt.setText("");
               
                
        }}
            catch (Exception e) {

                JOptionPane.showMessageDialog(this, "" + e.getMessage() + " Error,  Record Not Deleted!", "", JOptionPane.OK_OPTION);

            }
       
        
    }//GEN-LAST:event_deleteActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        reseting();
        disabling();
        
    }//GEN-LAST:event_resetActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        new Home_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Return_Book_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        new Home_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new Manage_Members_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new Manage_Books_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new Manage_Book_Lending().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        new Manage_Inventory_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new Manage_Newspaper_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new Manage_User_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Book_Lending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Book_Lending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Book_Lending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Book_Lending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Manage_Book_Lending().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DOBr;
    private com.toedter.calendar.JDateChooser DOD;
    private javax.swing.JButton addmember;
    private javax.swing.JButton back;
    private javax.swing.JTextField bookid;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField finetxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JTextField latedaystxt;
    private javax.swing.JTextField memberidtxt;
    private javax.swing.JTextField refnotxt;
    private javax.swing.JButton reset;
    private javax.swing.JButton search;
    private javax.swing.JTextField statues;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void enabling() {
       memberidtxt.setEnabled(true);
       memberidtxt.setEditable(false);
                        bookid.setEnabled(true);
                        bookid.setEditable(false);
                        DOBr.setEnabled(true);
                        
                        DOD.setEnabled(true);
                        statues.setEnabled(true);
                        statues.setEditable(false);
                        finetxt.setEnabled(true);
                        latedaystxt.setEnabled(true);
    }
     private void disabling() {
       memberidtxt.setEnabled(false);
                        bookid.setEnabled(false);
                       
                        DOBr.setEnabled(false);
                        
                        DOD.setEnabled(false);
                        statues.setEnabled(false);
                        finetxt.setEnabled(false);
                        latedaystxt.setEnabled(false);
                        
                        update.setEnabled(false);
                        delete.setEnabled(false);
    }
     
       private void reseting() {
       memberidtxt.setText("");
                        bookid.setText("");
                       
                        DOBr.setDate(null);
                        
                        DOD.setDate(null);
                        statues.setText("");
                        finetxt.setText("");
                        latedaystxt.setText("");
                        refnotxt.setText("");
    }
}
